<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;


class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            "hy"=>"Armenian",
            "aa"=>"Afar",
            "ab"=>"Abkhazian",
            "ae"=>"Avestan",
            "af"=>"Afrikaans",
            "ak"=>"Akan",
            "am"=>"Amharic",
            "an"=>"Aragonese",
            "ar"=>"Arabic",
            "as"=>"Assamese",
            "av"=>"Avaric",
            "ay"=>"Aymara",
            "ba"=>"Bashkir",
            "be"=>"Belarusian",
            "bg"=>"Bulgarian",
            "bh"=>"Bihari languages",
            "bi"=>"Bislama",
            "bm"=>"Bambara",
            "bn"=>"Bengali",
            "bo"=>"Tibetan",
            "br"=>"Breton",
            "bs"=>"Bosnian",
            "ce"=>"Chechen",
            "ch"=>"Chamorro",
            "co"=>"Corsican",
            "cr"=>"Cree",
            "cs"=>"Czech",
            "cv"=>"Chuvash",
            "cy"=>"Welsh",
            "da"=>"Danish",
            "de"=>"German",
            "dz"=>"Dzongkha",
            "ee"=>"Ewe",
            "en"=>"English",
            "eo"=>"Esperanto",
            "es"=>"Spanish",
            "et"=>"Estonian",
            "eu"=>"Basque",
            "fa"=>"Persian",
            "ff"=>"Fulah",
            "fi"=>"Finnish",
            "fj"=>"Fijian",
            "fo"=>"Faroese",
            "fr"=>"French",
            "fy"=>"Western Frisian",
            "ga"=>"Irish",
            "gd"=>"Gaelic",
            "gl"=>"Galician",
            "gn"=>"Guarani",
            "gu"=>"Gujarati",
            "gv"=>"Manx",
            "ha"=>"Hausa",
            "he"=>"Hebrew",
            "hi"=>"Hindi",
            "ho"=>"Hiri Motu",
            "hr"=>"Croatian",
            "hu"=>"Hungarian",
            "hz"=>"Herero",
            "id"=>"Indonesian",
            "ig"=>"Igbo",
            "ik"=>"Inupiaq",
            "io"=>"Ido",
            "is"=>"Icelandic",
            "it"=>"Italian",
            "iu"=>"Inuktitut",
            "ja"=>"Japanese",
            "jv"=>"Javanese",
            "ka"=>"Georgian",
            "kg"=>"Kongo",
            "kk"=>"Kazakh",
            "km"=>"Central Khmer",
            "kn"=>"Kannada",
            "ko"=>"Korean",
            "kr"=>"Kanuri",
            "ks"=>"Kashmiri",
            "ku"=>"Kurdish",
            "kv"=>"Komi",
            "kw"=>"Cornish",
            "la"=>"Latin",
            "lb"=>"Luxembourgish",
            "lg"=>"Ganda",
            "li"=>"Limburgan",
            "ln"=>"Lingala",
            "lo"=>"Lao",
            "lt"=>"Lithuanian",
            "lu"=>"Luba-Katanga",
            "lv"=>"Latvian",
            "mg"=>"Malagasy",
            "mh"=>"Marshallese",
            "mi"=>"Maori",
            "mk"=>"Macedonian",
            "ml"=>"Malayalam",
            "mn"=>"Mongolian",
            "mr"=>"Marathi",
            "ms"=>"Malay",
            "mt"=>"Maltese",
            "my"=>"Burmese",
            "na"=>"Nauru",
            "nb"=>"Norwegian",
            "ne"=>"Nepali",
            "ng"=>"Ndonga",
            "no"=>"Norwegian",
            "oj"=>"Ojibwa",
            "om"=>"Oromo",
            "or"=>"Oriya",
            "pi"=>"Pali",
            "pl"=>"Polish",
            "pt"=>"Portuguese",
            "qu"=>"Quechua",
            "rm"=>"Romansh",
            "rn"=>"Rundi",
            "ru"=>"Russian",
            "rw"=>"Kinyarwanda",
            "sa"=>"Sanskrit",
            "sc"=>"Sardinian",
            "sd"=>"Sindhi",
            "se"=>"Northern Sami",
            "sg"=>"Sango",
            "sk"=>"Slovak",
            "sl"=>"Slovenian",
            "sm"=>"Samoan",
            "sn"=>"Shona",
            "so"=>"Somali",
            "sq"=>"Albanian",
            "sr"=>"Serbian",
            "ss"=>"Swati",
            "su"=>"Sundanese",
            "sv"=>"Swedish",
            "sw"=>"Swahili",
            "ta"=>"Tamil",
            "te"=>"Telugu",
            "tg"=>"Tajik",
            "th"=>"Thai",
            "ti"=>"Tigrinya",
            "tk"=>"Turkmen",
            "tl"=>"Tagalog",
            "xh"=>"Xhosa",
            "yi"=>"Yiddish",
            "yo"=>"Yoruba",
            "zh"=>"Chinese",
            "zu"=>"Zulu"
        ];

        foreach ($countries as $key => $country) {
            Country::updateOrCreate([
                'key' => $key,
                'name' => $country
            ]);

        }
    }
}
