<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */

    'junior' => 'Դեռահաս',
    'junior_info' => 'Մինչև 18 տարեկան',
    'young' => 'Երիտասարդ',
    'young_info' => '19 - 60 տարեկան',
    'old' => 'Տարեց',
    'old_info' => '61 և ավելի տարեկան',
    'unknown' => 'Անհայտ',
    'unknown_info' => 'ռարիքը նշված չէ'

];


