<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */


    "all" => "Բոլորը",
    "store" => "Ստեղծել",
    "update" => "Փոփոխել",
    "change_status" => "Կարգավիճակի փոփոխում",
    "delete" => "Ջնջել",
    "return" => "Վերադարձ"

];
