<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */

    'standart' => 'Ստանդարտ',
    'discount' => 'Զեղչված',
    'free' => 'Անվճար',
    'united' => 'Միասնական',
    'subscription' => 'Աբոնեմենտ',
    'event' => 'Միջոցառում',
    'corporative' => 'Կորպորատիվ',
    'educational' => 'Կրթական ծրագիր',
    'guide' => 'Էքսկուրսիա',
    'canceled' => 'Չեղարկված',
    'product' => 'Ապրանքներ'

];
 
