<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */

  'failed' => 'Այս հավատարմագրերը չեն համապատասխանում մեր գրառումներին:',
  'password' => 'Տրամադրված գաղտնաբառը սխալ է:',
  'throttle' => 'Չափից շատ մուտք գործելու փորձեր: Խնդրում եմ նորից փորձեք :seconds վայրկյանից։'

];
