<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */

  'educational_programs' => 'Կրթական ծրագիր',
  'users' => 'Օգտագործողներ',
  'museum' => 'Թանգարան',
  'product' => 'Ապրանքներ',
  'new' => 'Նորություն'


];
