<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */

    'super_admin' => 'Գլխավոր ադմինիստրատոր',
    'general_manager' => 'Կառավարման գլխավոր օպերատոր',
    'chief_accountant' => 'Գլխավոր ֆինանսական օպերատոր',
    'head_technic' => 'Գլխավոր տեխնիկական հրահանգիչ',
    'museum_admin' => 'Թանգարանի տնօրեն',
    'manager' => 'Կառավարող օպերատոր',
    'accountant' => 'Ֆինանսական օպերատոր',
    'cashier' => 'Դրամարկղի վաճառող',
    'content_manager' => 'Բովանդակության կառավարիչ',
    'technical_manager' => 'Տեխնիկական հրահանգիչ',
    'visitor' => 'Այցելու'

];
