name: Deploy with SSH and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Deploy to server via SSH and Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd /home/webex/Museum/Museums &&
          git checkout . && git pull origin main
          docker-compose down &&
          docker rmi -f webex &&
          docker-compose up -d --build"
